name: DispatcherWindowsCI
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Environment dependencies
        run: |
          choco install exiftool
          go version
          go get -v ./...
      - name: Tests
        run: go test ./...